/*
 * pru/pru_comms.c  --  HOW THE LINUX SIDE TALKS TO THE PRU  (plain-English draft)
 *
 * You do NOT need to understand every C line to use this. Read the English
 * comments top-to-bottom once; they ARE the "logic" you said you were missing.
 *
 * ----------------------------------------------------------------------------
 * THE BIG IDEA (read this first)
 * ----------------------------------------------------------------------------
 * The PRU (tiny processor) and the main Linux CPU CANNOT call each other's
 * functions. They are two separate computers on one chip.
 *
 * So how does Linux tell the PRU "move the servo to 90 degrees"?
 *   -> They share a block of RAM (memory) that BOTH can read and write.
 *   -> Think of it as a WHITEBOARD pinned between two rooms.
 *   -> Linux writes a number on the whiteboard.
 *   -> The PRU walks past the whiteboard, reads the number, and acts on it.
 *   -> Neither knocks on the other's door. They just use the whiteboard.
 *
 * That shared whiteboard is PRU shared RAM.
 *   - In the PRU's OWN address space it is at  0x00010000  (see pru_servo.c).
 *   - In the Linux ARM CPU's address space it is at 0x4A310000.
 * Same physical block, two door numbers. (Like two people calling one room
 * "Room 5" vs "Suite 5".)
 *
 * ----------------------------------------------------------------------------
 * THE CONTRACT (must match pru_servo.c EXACTLY)
 * ----------------------------------------------------------------------------
 * Both sides agree on this layout in memory (a "struct"):
 *     uint32_t magic;    // password 0x50524F55 ("PROU") = "I am alive, layout ok"
 *     uint32_t pan_us;   // PAN pulse width in microseconds  (500..2500)
 *     uint32_t tilt_us;  // TILT pulse width in microseconds (500..2500)
 *     uint32_t seq;      // bump by 1 each time Linux writes new angles
 *     uint32_t flags;    // spare (future STOP flag etc.)
 *
 * ----------------------------------------------------------------------------
 * FUNCTION 1:  pru_init()   -- open the whiteboard (call ONCE at startup)
 * ----------------------------------------------------------------------------
 *   Step-by-step (English):
 *     1. Open the special file "/dev/mem". On Linux, /dev/mem is a window that
 *        lets a program peek at PHYSICAL memory addresses. Opening it = getting
 *        the key to the whiteboard room.
 *     2. Use mmap() to MAP physical address 0x4A310000 into our program's own
 *        memory space. After mmap, we read/write that memory using a normal C
 *        pointer -- no special instructions needed.
 *     3. Write the magic password 0x50524F55 ("PROU") so the PRU firmware knows
 *        the Linux side is alive and the layout matches.
 *     4. Return a handle/pointer the rest of the program will reuse.
 *  
 * ----------------------------------------------------------------------------
 * FUNCTION 2:  pru_set_angle(axis, angle_degrees)  -- write a command
 * ----------------------------------------------------------------------------
 *   Step-by-step (English):
 *     1. Convert the human angle (0..180) into a pulse width in microseconds
 *        (500..2500 us) using the standard servo formula.
 *     2. Pick WHICH slot on the whiteboard to write:
 *          axis == PAN  -> write into pan_us
 *          axis == TILT -> write into tilt_us
 *     3. Write the pulse-width number into that slot.
 *     4. Bump the 'seq' counter by 1 so the PRU can tell a NEW command arrived
 *        vs an OLD one it already acted on.
 *   That's it. Linux never touches a pin. It just writes a number.
 *
 * ----------------------------------------------------------------------------
 * FUNCTION 3:  pru_stop()  -- tell the PRU to park & halt (used by stop mode)
 * ----------------------------------------------------------------------------
 *   Step-by-step (English):
 *     1. Write a "STOP" flag into the 'flags' slot (or set angles to centre).
 *     2. The PRU firmware, next time it reads the whiteboard, parks the servo
 *        at centre and can idle / exit.
 *
 * ----------------------------------------------------------------------------
 * WHAT THE PRU FIRMWARE DOES ON ITS SIDE (mirror image, see pru_servo.c)
 * ----------------------------------------------------------------------------
 *   - At boot it points at the whiteboard at 0x00010000.
 *   - Every loop it checks magic == "PROU".
 *   - It reads pan_us / tilt_us and calls pulse() for each pin (P9_31 / P9_30)
 *     using __R30 (the light-switch register).
 *   - It never asks Linux for anything; it just reads the whiteboard.
 *
 * ----------------------------------------------------------------------------
 * WHY THIS IS SAFE / WHY WE USE IT
 * ----------------------------------------------------------------------------
 *   - The servo pulse is generated by the PRU (200 MHz, never interrupted), so
 *     it is rock-steady -- no buzz, no jitter -- even while Linux is busy with
 *     the camera.
 *   - Linux only writes a few numbers; if Linux crashes, the PRU keeps emitting
 *     the last pulse, so the servo just holds position.
 *
 * (This file now contains the REAL C implementation, not just a scaffold. It is
 *  compiled into the turret binary via pru/pru_comms.o in the top-level Makefile.
 *  The "Step-by-step" English notes above each function describe what the code
 *  below does, in plain language.)
 */

 #include <stdint.h>
 #include <stdio.h>
 #include <stdlib.h>
 #include <fcntl.h>
 #include <sys/mman.h>
#include <unistd.h>
 #include "pru_comms.h"

 #define PRU_SHARED_RAM_PHYS 0x4A310000
 static volatile uint32_t *mmap_ptr = NULL; 


int pru_init(void) {

     /* Step 1: open /dev/mem */
     /* Step 2: mmap() the physical address 0x4A310000 into our process space */
     /* Step 3: write magic password 0x50524F55 ("PROU") */
     /* Step 4: return a handle/pointer for later use */

     int fd = open("/dev/mem", O_RDWR | O_SYNC);
        if (fd < 0) {
            perror("pru_init: open /dev/mem");
            exit(1);
        }
        mmap_ptr = mmap(NULL, 0x1000, PROT_READ | PROT_WRITE, MAP_SHARED, fd, 0x4A310000);
        if (mmap_ptr == MAP_FAILED) {
            perror("pru_init: mmap");
            close(fd);
            exit(1);
        }
        /* Initialise the board BEFORE writing the magic password, so the PRU
           only ever sees valid data: park both servos at centre (1500 us) and
           mark seq = 1 so the very first pru_set_angle() is seen as "new". */
        mmap_ptr[1] = 1500; /* pan_us  = centre */
        mmap_ptr[2] = 1500; /* tilt_us = centre */
        mmap_ptr[3] = 1;    /* seq */
        mmap_ptr[4] = 0;    /* flags */
        /* Write the magic password LAST so the firmware won't act on garbage */
        mmap_ptr[0] = 0x50524F55; /* "PROU" */
        close(fd);

        return 0;   /* 0 = success; the real handle lives in static mmap_ptr */
       
 }  

 void pru_set_angle(pru_axis_t axis, float angle_degrees) {
     /* Step 1: convert angle to pulse width in microseconds */
     /* Step 2: write to the correct slot (pan_us or tilt_us) */
     /* Step 3: bump the seq counter */

     if (mmap_ptr == NULL) {
         fprintf(stderr, "pru_set_angle: PRU not initialized\n");
         return;
     }

     unsigned long pulse_width_us = (unsigned long)(500 + (angle_degrees / 180.0) * 2000);
     if (axis == PAN) {
         mmap_ptr[1] = pulse_width_us; /* pan_us */
     } else if (axis == TILT) {
         mmap_ptr[2] = pulse_width_us; /* tilt_us */
     }
     mmap_ptr[3]++; /* bump seq counter */
 }

 void pru_stop(void) {
     /* The current firmware does NOT read the flags slot, so writing a STOP
      * flag alone would do nothing. To actually park, write CENTRE (1500 us)
      * to both axes and bump seq -- the firmware will then re-pulse at centre
      * on its next loop and the servo holds still in the middle. */
     if (mmap_ptr == NULL) {
         fprintf(stderr, "pru_stop: PRU not initialized\n");
         return;
     }
     mmap_ptr[1] = 1500; /* pan_us  = centre */
     mmap_ptr[2] = 1500; /* tilt_us = centre */
     mmap_ptr[3]++;      /* bump seq so the PRU re-reads */
 }